[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_untyped_calls = true
check_untyped_defs = true
exclude = "src/opik_optimizer/mipro_optimizer/"

[[tool.mypy.overrides]]
# Mixins access attributes provided by the concrete optimizer class at runtime.
# Suppress attr-defined for these modules to avoid false positives.
module = [
  "opik_optimizer.evolutionary_optimizer.*",
]
disable_error_code = ["attr-defined"]


[tool.uv]
managed = false
